### ISSUE TITLE
Detail on program page of website needs update

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2016#17]
**This:**

In the meantime, here is the outline of the program:
September 22nd 7PM: opening social for early arrivers in Brussels 
September 23rd: first main conference day with presentations and discussions 
September 24th: second main conference day with presentations and discussions 
September 25th: hack day with code, documentation sprints, mapping activities and workshops 

**Needs updating to this:**

In the meantime, here is the outline of the program:
September 22nd 7PM: opening social for early arrivers in Brussels / those who join us from HOT Summit (http://summit.hotosm.org/)
September 23rd: first main conference day with presentations and discussions 
September 24th: second main conference day with presentations and discussions 
September 25th: get hands on with workshops, code, documentation sprints and mapping activities.

**Comment by RobJN** [comment]
@xivk What is the status of a Monday 26th Hackday with the FOSS community? Are we sufficiently far advanced to announce anything?

**Comment by mikelmaron** [comment]
updated @RobJN
