### ISSUE TITLE
Add web analytics

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2016#18]
Hi @tatsvc. I don't think we have any web analytics (e.g. Google analytics) on the SotM website. Can you add it please.

**Comment by tatsvc** [comment]
Feel free to also add it yourself! I won't be able to hit any sotm work this week 😔

**Comment by RobJN** [comment]
OK no worries. Working with @mikelmaron I think we've figured it out.

Code needed was shared with Mikel (can't get it to display here) and according to [this](http://www.ericmobley.net/guide-to-tracking-multiple-subdomains-in-google-analytics/) it should track all subdomains so no issue there.

**Comment by althio** [comment]
HOT-OSM uses piwik instead of Google Analytics.
I think someone at the OSMF runs piwik https://piwik.openstreetmap.org/?
​

**Comment by RobJN** [comment]
Thanks. Just wrote to Grant + Tom. Will share if they respond. I assume piwik is just as easy.

**Comment by mikelmaron** [comment]
I added Google Analytics tracking with this commit https://github.com/openstreetmap/stateofthemap-2016/commit/7ba30e341fd68681e8be0454c0c1cb0d647bbdf7

If we end up switching to piwik, just remove the above change and replace with the piwik code.

**Comment by RobJN** [comment]
Thanks. Tom sorted out Piwik for me so I've created a PR for this now. I don't have write access so can you accept this please.
