### ISSUE TITLE
Map attribution is missing

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/stateofthemap-2016#2]
There's no attribution shown for the map.

There's an element added to the map containing the correct attribution:

https://github.com/openstreetmap/stateofthemap-2016/blob/9008c466f85ce3b04daa4d427a4a9e8b1fd7cb6f/_includes/map.html#L17-L21

However, there's also a stylesheet rule that hides it:

https://github.com/openstreetmap/stateofthemap-2016/blob/9008c466f85ce3b04daa4d427a4a9e8b1fd7cb6f/_includes/css/sotm2016.css#L496-L498

I guess the stylesheet rule was intending to hide something else! It's not clear from the [commit](https://github.com/openstreetmap/stateofthemap-2016/commit/efa3f19960a8fbab686a2bb65e472cc9f8fb56de) what was intended so I haven't made a PR.

**Comment by mikelmaron** [comment]
Strange, I see the attribution. @gravitystorm still a problem?

cc @tatsvc

**Comment by tatsvc** [comment]
It's back!

**Comment by gravitystorm** [comment]
https://github.com/openstreetmap/stateofthemap-2016/commit/7db0bd3eb382930e712683ef39707da7277e9428 was the fix
