### ISSUE TITLE
Sponsor updates required

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2016#28]
@mikelmaron @tatsvc 

Here are the next batch of sponsor updates for the website:
1. [Open Transport Net](http://www.opentransportnet.eu/home): A SILVER sponsor. Let me know if we need a high quality logo from them. Logo with url link on the site please.
2. [Geofabrik](http://www.geofabrik.de/) (Supporter). Just the name and url on our site please.
3. [Telenav](http://www.telenav.com/) (Supporter). Just the name and url on our site please.

**Comment by RobJN** [comment]
1. Digital Globe: A Bronze sponsor so logo with url link.

**Comment by althio** [comment]
name: DigitalGlobe
URL: www.digitalglobe.com
logo:
[DGLogo_BlackOnlyCMYK_Std.eps.zip](https://github.com/openstreetmap/stateofthemap-2016/files/355673/DGLogo_BlackOnlyCMYK_Std.eps.zip)

![event-featured-image-c69f5f5b66bcd4ac1ac6f60a17b85ad0](https://cloud.githubusercontent.com/assets/9863567/16709410/576999a8-4610-11e6-94cc-2a8fe0aba41f.jpg)
![dg-logo-color](https://cloud.githubusercontent.com/assets/9863567/16709411/5772e6de-4610-11e6-95aa-cb1965c7e71d.png)
![logo_globe_swir](https://cloud.githubusercontent.com/assets/9863567/16709412/57823fda-4610-11e6-92b8-099567bbf0f1.png)

**Comment by althio** [comment]
Best I could find for Open Transport Net - OTN logo

![OTN_xl](https://cloud.githubusercontent.com/assets/9863567/16838859/e96bd140-49cb-11e6-89cd-65bb163949fe.jpg)

Ping @tatsvc please ask if we need something more for any sponsors.

**Comment by tatsvc** [comment]
https://github.com/openstreetmap/stateofthemap-2016/pull/35
