### ISSUE TITLE
Set up Sunday program

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2016#34]
Hi @tatsvc. Did @mikelmaron mention working on website side of the Sunday program for State of the Map? He had suggested he would ask you if you had any time free on Wednesday.

The Sunday program is a bit more complicated than the first two days:
- We will have 6 tracks available.
- Each track has 2 morning sessions and 2 afternoon sessions. Times are according to [this table](https://docs.google.com/spreadsheets/d/1iqdjgOHzDhNyDl-M8-SUbhsAySVViJ1t1_AyNmUUz9o/edit#gid=1449959141) (see the far right hand side of the "Timetable" worksheet).
- We will be leaving some gaps in the program so that we can have BoF sessions.
- Currently, from those workshops that are scheduled, we never have more than 4 things running at the same time. The rooms do however differ. (This means that you may get away with showing a 4 track set-up as long as the rooms can be varied).

Can you please set the site up for this. If you could do the logic/backend I can then provide the details/new files needed in https://github.com/openstreetmap/stateofthemap-2016/tree/gh-pages/_posts/schedule

Does that seem like a good approach?

**Comment by tatsvc** [comment]
Hey @RobJN, sorry for the late response here! I've been super swamped with SOTM US work! I will look at this (hopefully) tomorrow!

**Comment by tatsvc** [comment]
Pulled in @katydecorah to set up a 6-track structure for sunday!
