### ISSUE TITLE
Next sponsor updates

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2016#39]
More! :+1: No rush, post SotM US fine.
## CARTO

At Bronze level please.
[CartoLogo.zip](https://github.com/openstreetmap/stateofthemap-2016/files/374652/CartoLogo.zip)

**Comment by althio** [comment]
with target URL: https://carto.com

**Comment by althio** [comment]
Another to add please!

## SNCF Transilien

Bronze level

logo
[SNCF_Logo2011.zip](https://github.com/openstreetmap/stateofthemap-2016/files/407038/SNCF_Logo2011.zip)

target
http://www.sncf.com/

**Comment by RobJN** [comment]
## Telenav

They need moving from Supporter to Silver.

## Navmii

Silver level.

@tatsvc : Up to 4 now so an update would be good soon. Do you have the assets you need for Telenav & Navmii?

**Comment by althio** [comment]
high resolution **Navmii** logo available for download here: https://www.dropbox.com/s/ittw18bokfya1sm/navmiiLogoLandscape_OSM.ai?dl=0
target: not specified, by default: http://navmii.com/

if nothing better for Telenav: https://pbs.twimg.com/profile_images/1743605887/Scout_Paint_2.png

**Comment by tatsvc** [comment]
I'll make an update today!

**Comment by tatsvc** [comment]
done! http://2016.stateofthemap.org/
