### ISSUE TITLE
Bad ordering

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2016#42]
Hi @tatsvc. The program is ordering alphabetically by title rather than by track. Examples:

![wrong order0](https://cloud.githubusercontent.com/assets/5060210/17196643/08488012-545e-11e6-8382-c072d80a6486.png)
![wrong order1](https://cloud.githubusercontent.com/assets/5060210/17196644/0849e54c-545e-11e6-8d2f-6d107988ec44.png)

What am I doing wrong? Is this something that you can fix quite easily?

**Comment by tatsvc** [comment]
Oh hmmm. I'm on vacation in canada this week, so I can't look into this any time soon. @katydecorah might be able to help out 😁
