### ISSUE TITLE
feedback on text selection

### ISSUE THREAD

**Issue by althio** [openstreetmap/stateofthemap-2016#58]
Feedback from user by email

> At first it seems that I can't select any text. I am aware that there are some CSS "features" to prevent text selection, but it turns out you're not using that. Actually, it is possible to select text, but there's no clear visual indication that text has been selected.
> 
> This is caused by this rule in your CSS:
> 
> `::selection {
>     text-shadow: none;
>     background: #fcfcfc;
>     background: rgba(255,255,255,.2);
> }`
> 
> Please remove this CSS. It makes the site harder to use and frustrates sharing of information.

**Comment by joostschouppe** [comment]
Fixed; @mikelmaron already answered the user.
