### ISSUE TITLE
date and time to each card, anchors to the program

### ISSUE THREAD

**Issue by althio** [openstreetmap/stateofthemap-2016#67]
from @Zverik

> Hi SOTM Team,
> 
> I was going to link to an event card from the State of the Map 2016 program, but noticed there are no dates and times on these. For example, http://2016.stateofthemap.org/2016/osm-for-traffic-simulation/ — just the length, no other numbers.
> 
> There are also no ids on days and any elements in the program table, so I cannot use anchors to link to specific times or events.
> 
> Could you please add date and time to each card? And maybe anchors to the program source.

**Comment by althio** [comment]
- [x] date and time to each card, fixed by @mikelmaron https://github.com/openstreetmap/stateofthemap-2016/pull/68 + https://github.com/openstreetmap/stateofthemap-2016/pull/69
- [ ] anchors to program, comment by @mikelmaron 'got tricky styling wise'

**Comment by Firefishy** [comment]
Closing historical issue.
