### ISSUE TITLE
Program timing issues on Sunday

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2016#72]
We set all Sunday workshops to 75 minutes (originally we had a mix on 60 and 90 minute sessions) but the program didn't get updated:

See right of Ilya's name:
![selection_001](https://cloud.githubusercontent.com/assets/5060210/18295006/aafe7382-7495-11e6-86b5-0f15965f1c82.png)

Also on the main page it says 30 minutes:
![selection_002](https://cloud.githubusercontent.com/assets/5060210/18295031/d9435c76-7495-11e6-8b36-dae5fbca6344.png)

@mikelmaron I couldn't see where this was coming from. Can you take a look please.

**Comment by althio** [comment]
I _think_ it comes from
/_layouts/event.html with

```
<h3 class='inline event-title'>{{page.name}}
              {% if page.length %}
                <small class='inline'>{{page.length}}</small>
              {% else %}
                <small class='inline pad1x'>{% if page.length %}{{page.length}}{% elsif page.track %}1hour{% else %}30min{% endif %}</small>
              {% endif %}
            </h3>
```

If I understand correctly, we could add
`length: xx min` to each session where duration is not well found. Or maybe something more clever to determine it automatically in the code above.

**Comment by mikelmaron** [comment]
Fixed. Only items that have "track" set are Sunday sessions. Display 75 minutes for these.

https://github.com/openstreetmap/stateofthemap-2016/blob/gh-pages/_includes/slot-item-small.html#L13
