### ISSUE TITLE
Sort order wrong

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2016#74]
On Saturday the details are right but the display order is wrong. We should have the A room on the left, C room in the middle. Kevin and Sajjad in room A is correct.

We had a similar issue with the workshops - it's just a sort order issue. Sorry I spotted this earlier but forgot about it. Joost just reminded me.

cc: @mikelmaron @tatsvc 

![prog](https://cloud.githubusercontent.com/assets/5060210/18315390/c3434480-750e-11e6-84f9-8031e2f0bc19.png)

**Comment by mikelmaron** [comment]
fixed
