### ISSUE TITLE
video stream

### ISSUE THREAD

**Issue by mikelmaron** [openstreetmap/stateofthemap-2016#79]
Here are the links for the video streams. These should be added to the website.

Day 1 room A 08:50 AM https://www.youtube.com/watch?v=tMV4V0KsKzE
Day 1 room C 09:50 AM https://www.youtube.com/watch?v=YQJUlUdQfZc
Day 2 room A 09:50 AM https://www.youtube.com/watch?v=iuYx8ESZzHA
Day 2 room C 09:50 https://www.youtube.com/watch?v=yTJpUjuQZME
Day 3 room QA 09:50 https://www.youtube.com/watch?v=nwp2Ppq3D08
Day 3 room QC 09:50 https://www.youtube.com/watch?v=nwp2Ppq3D08

I've asked them to rename all the rooms QA or QC, and to rename the channel State of the Map 2016.

**Comment by harry-wood** [comment]
Those have been added. Close this
