### ISSUE TITLE
add video embeds

### ISSUE THREAD

**Issue by mikelmaron** [openstreetmap/stateofthemap-2016#86]
Just add a property in the header "youtube_recording" with the video id. For example, https://github.com/openstreetmap/stateofthemap-2016/commit/35bd2e65b08d5e9b99901465f916322965a2b9ea

You probably want to update the title on YouTube as well.

Once we're all done, we should update the video streams section on the front page, and make a blog post

@joostschouppe @RobJN

**Comment by nomoregrapes** [comment]
This should all be done now with pull request https://github.com/openstreetmap/stateofthemap-2016/pull/87

**Comment by althio** [comment]
Need to add several videos in one page:

Frederik, Mechanical Edits in OpenStreetMap
https://www.youtube.com/watch?v=ZrvcVAPdaWI
SImon, What keeps you from inadvertently screwing up OpenStreetMap?
https://www.youtube.com/watch?v=3wg0P32QhO4

on page http://2016.stateofthemap.org/2016/staying-on-the-right-side-best-practices-in-editing/

**Comment by nomoregrapes** [comment]
Thanks for the links Benoit. I'll try update the site at lunchtime.

**Comment by Firefishy** [comment]
Closing historical issue.
