### ISSUE TITLE
May 3 Updates

### ISSUE THREAD

**Issue by mikelmaron** [openstreetmap/stateofthemap-2016#9]
- [x] Add link to registration post on website. https://blog.openstreetmap.org/2016/05/02/registration-is-now-open-for-state-of-the-map/
- [x] Add new sponsors (will gather logos and links below)
- [x] Add links to existing sponsors https://github.com/openstreetmap/stateofthemap-2016/issues/8 (will gather links and add below)

@tatsvc

**Comment by mikelmaron** [comment]
@RobJN @althio could you gather all the new sponsor logos and links in one list?

**Comment by althio** [comment]
Re:logos

Do you mean paste logos directly on this issue?
(I asked how to deal with logo storage here https://github.com/osmbe/sotm2016/issues/29#issuecomment-206952982)

www.mapbox.com
maps.me/en/home
https://www.and.com/
http://www.mapillary.com/
http://www.msf.org.uk/
http://mousebird.github.io/mousebird/
https://www.jawg.io

**Comment by mikelmaron** [comment]
@althio can you confirm that all of these are Bronze, except Mapbox at Gold?

For logos, yes, attach here. I only think that works for images -- if they provided a logo in SVG (which is preferred anyway) then send me an email with the files attached.

cc @tatsvc

**Comment by althio** [comment]
@RobJN can you confirm?
To the best of my knowledge:

| Sponsor | Rank | website |
| --- | --- | --- |
| Mapbox | _**Gold**_ | www.mapbox.com |
| Mapzen | **Silver** | https://mapzen.com/ (https://github.com/osmbe/sotm2016/issues/74) |
| Maps Me | **Bronze** + Exhibition | http://maps.me/en/home |
| Mapillary | **Bronze** + Exhibition | http://www.mapillary.com/ |
| MSF | **Bronze** | [TBC] http://www.msf.org.uk/ |
| Jawg | **Bronze** | https://www.jawg.io |
| AND | **Bronze** | [EDITED] https://www.and.com/services/openstreetmap/ |
| Facebook ? | **Bronze**? | [TBC] |
| Mousebird | Supporter + Exhibition | http://mousebird.github.io/mousebird/ |

**Comment by tatsvc** [comment]
I started working on this in this PR: https://github.com/openstreetmap/stateofthemap-2016/pull/11

But can someone reach out to Jawg and AND for better logos, I can't work with what I can find on their site/the internet. Preferable svgs. Or just bigger files would already help a lot.

**Comment by RobJN** [comment]
Have just sent them both an email.

Rob

**Comment by althio** [comment]
I have these because they are also sponsors for SotM-France:
![jawg_logo_ebiz](https://cloud.githubusercontent.com/assets/9863567/15050661/596b993e-12f5-11e6-9409-16ea0749ccb7.png)
![mapillary-logo-black 1x-440x113](https://cloud.githubusercontent.com/assets/9863567/15050779/f1e868b8-12f5-11e6-8e77-b773a730e4c0.png)
[mapillary-logo-black@1x.svg.zip](https://github.com/openstreetmap/stateofthemap-2016/files/250815/mapillary-logo-black.1x.svg.zip)
There is also a rather bigger JAWG logo .ai file (2 MB) if the png is not enough.

**Comment by tatsvc** [comment]
@althio thanks, the png was fine:

![image](https://cloud.githubusercontent.com/assets/2894119/15051832/9f49e884-12c8-11e6-9396-9377f1779eb1.png)

**Comment by althio** [comment]
@tatsvc The company AND replied to Rob:

> Hereby our logo to put on the website and/or print.
> You can link our logo to the following path: https://www.and.com/services/openstreetmap/

![and_1-pms](https://cloud.githubusercontent.com/assets/9863567/15110405/fe414448-15e0-11e6-88a3-0237783a9d88.jpg)
[AND_1-pms.eps.zip](https://github.com/openstreetmap/stateofthemap-2016/files/254748/AND_1-pms.eps.zip)

**Comment by tatsvc** [comment]
Thank you! I'll try to add these later today (I'm on SF time for the week now)

**Comment by mikelmaron** [comment]
@tatsvc are we only missing a Facebook logo? Can you just find one, or need something from them?

**Comment by tatsvc** [comment]
yeah I can find that one!

**Comment by RobJN** [comment]
@tatsvc Can you put Mapzen's logo on as well please (Silver sponsor). https://mapzen.com/media-resources/

**Comment by tatsvc** [comment]
![image](https://cloud.githubusercontent.com/assets/2894119/15323526/739a9e58-1c10-11e6-8aa2-d03dc5a763b4.png)
