### ISSUE TITLE
video links on the main page

### ISSUE THREAD

**Issue by harry-wood** [openstreetmap/stateofthemap-2016#90]
The site homepage currently links the unedited day long videos. We should link... something better there.

I found this youtube playlist
https://www.youtube.com/playlist?list=PLQNy8KsDknCr92fIXYcOKL42U35wRAV9Y
So something like that could be linked.

I was trying to work out a few things about this though which I'm not clear on:  Is the video editing complete, all clips up on youtube for all sessions? or there's more to be published still? Are there more youtube playlists, one for each room at the conference? I couldn't find them, in fact I can't quite remember how I stumbled across this first one.

Great to see the edited session videos appearing now linked off the session pages. Great work by the video editing team to get that sorted (I know it takes more effort that people tend to imagine!) Let's get them linked better!

**Comment by RobJN** [comment]
@nomoregrapes (Gregory M) and @joostschouppe are in the process of linking all of the videos to the program pages. You will need to check in with them as to the progress.

**Comment by nomoregrapes** [comment]
We should update the message on the homepage, to direct people to the schedules for videos now.

**Comment by Firefishy** [comment]
Closing historical issue.
